Packaged examples
radxa-pkg/rknn_model_zoo pull request #2
Opened 2024-01-31 03:12 UTC by CodeChenL

2024-02-02 09:00 UTC, RadxaYuntian requested changes

2024-02-02 09:00 UTC, RadxaYuntian commented on .github/workflows/new_version.yml
> +    runs-on: ubuntu-22.04
`ubuntu-latest`

2024-02-02 09:00 UTC, RadxaYuntian commented on .github/workflows/new_version.yml
> +          git devscripts lintian wget
`build-essential`和`git`是默认就有的，其他三个放到`Build-Depends`

2024-02-02 09:00 UTC, RadxaYuntian commented on .github/workflows/new_version.yml
> +          make deb
`make all test deb`和我们其他的项目保持一致

2024-02-02 09:00 UTC, RadxaYuntian commented on .github/workflows/new_version.yml
> +          wget https://github.com/airockchip/rknn-toolkit2/raw/master/rknn-toolkit2/packages/requirements_cp310-1.6.0.txt
这个有必要么？难道不是whl里面自动包含依赖关系？

2024-02-02 09:00 UTC, RadxaYuntian commented on .github/workflows/release.yml
类似new_version.yaml修改

2024-02-02 09:00 UTC, RadxaYuntian commented on .gitignore
> +debian/rknn-model-zoo.debhelper.log
结尾空行

2024-02-02 09:00 UTC, RadxaYuntian commented on .gitignore
> +debian/rknn-model-zoo.debhelper.log
这里的东西参考我们其他仓库的debian/.gitignore

2024-02-02 09:00 UTC, RadxaYuntian commented on Makefile
1. 补充build和test的对象（test可以为空
2. 用makefile重写build对象：
```Makefile
YOLOV8 := yolov8_rk3588.rknn yolov8_rk3568.rknn
yolov8_rk3568.rknn: yolov8n.onnx
    python3 convert.py $@ rk3568 i8 $<
yolov8n.onnx:
    bash ./download_model.sh
```
类似这样

2024-02-02 09:00 UTC, RadxaYuntian commented on debian/control
> +#Vcs-Git: https://salsa.debian.org/debian/rknn-model-zoo.git
```suggestion
```

2024-02-02 09:00 UTC, RadxaYuntian commented on debian/control
> + and using `Python API` and `CAPI` to infer the RKNN model.
结尾空行

2024-02-02 09:00 UTC, RadxaYuntian commented on debian/control
> +Package: rknn-model-zoo
要添加多个包：rknn-model-zoo-rk3588,rknn-model-zoo-rk3568等

2024-02-02 09:00 UTC, RadxaYuntian commented on debian/copyright
> +Source: <https://github.com/airockchip/rknn_model_zoo>
```suggestion
Source: <https://github.com/radxa-pkg/rknn_model_zoo>
```

2024-02-02 09:00 UTC, RadxaYuntian commented on debian/copyright
> +Copyright: © 2022 Radxa Computer Co., Ltd
```suggestion
Copyright: © 2024 Radxa Computer Co., Ltd
```

2024-02-02 09:00 UTC, RadxaYuntian commented on debian/patches/0003-Adding-declarations-to-shell-script.patch
我看你这边添加了可执行bit，然后为了解决lintian警告添加了shebang。有没有可能直接通过bash执行，避免修改可执行属性？

2024-02-02 09:00 UTC, RadxaYuntian commented on debian/upstream/metadata
既然创建了这个文件那就把对应的值填上

2024-02-02 09:00 UTC, RadxaYuntian commented on debian/rules
多余的注释删掉

2024-02-02 09:17 UTC, CodeChenL commented on .github/workflows/new_version.yml
> +    runs-on: ubuntu-22.04
这里设置版本是为了不想某天latest更新了版本，导致python3版本更新导致ci安装的rknn-toolkits2（不同的python版本需要使用不同的rknn-toolkits2安装包和依赖）报错

2024-02-02 09:24 UTC, CodeChenL commented on .github/workflows/new_version.yml
> +          wget https://github.com/airockchip/rknn-toolkit2/raw/master/rknn-toolkit2/packages/requirements_cp310-1.6.0.txt
官方文档是这么做的

2024-02-02 09:27 UTC, RadxaYuntian commented on .github/workflows/new_version.yml
> +          wget https://github.com/airockchip/rknn-toolkit2/raw/master/rknn-toolkit2/packages/requirements_cp310-1.6.0.txt
lite就没有这个文件，我觉得应该可以试一试

2024-02-02 09:28 UTC, RadxaYuntian commented on .github/workflows/new_version.yml
> +          wget https://github.com/airockchip/rknn-toolkit2/raw/master/rknn-toolkit2/packages/requirements_cp310-1.6.0.txt
我也再看看whl格式是怎么回事

2024-02-02 09:30 UTC, RadxaYuntian commented on .github/workflows/new_version.yml
> +          wget https://github.com/airockchip/rknn-toolkit2/raw/master/rknn-toolkit2/packages/requirements_cp310-1.6.0.txt
![image](https://github.com/radxa-pkg/rknn_model_zoo/assets/95260730/c7207750-4939-49bc-bde3-6a07ecc07a79)
whl里面有完整依赖，不需要下requirements.txt

2024-02-02 09:32 UTC, CodeChenL commented on .github/workflows/new_version.yml
> +          wget https://github.com/airockchip/rknn-toolkit2/raw/master/rknn-toolkit2/packages/requirements_cp310-1.6.0.txt
好吧，可能是运行非rknn模型例程的依赖

2024-02-02 11:06 UTC, CodeChenL commented on debian/patches/0003-Adding-declarations-to-shell-script.patch
加可执行权限也是为了解决lintian警告（shell脚本没有执行权限）

2024-02-02 11:09 UTC, RadxaYuntian commented on debian/patches/0003-Adding-declarations-to-shell-script.patch
这个比我想象中多，而且可能不好维护。要不还是在lintian里面忽略了算了
另外写lintian-overrides时要记得用注释写明原因

2024-02-02 12:29 UTC, CodeChenL commented on debian/patches/0003-Adding-declarations-to-shell-script.patch
不用加了，现在貌似不报错了，可能那个时候有什么产物没清掉

2024-02-04 07:23 UTC, RadxaYuntian commented on .github/workflows/new_version.yml
> +    runs-on: ubuntu-22.04
就是希望它尽早报错尽早修复，而不是到了最后一天才知道有着一回事

2024-02-04 07:29 UTC, CodeChenL commented on .github/workflows/new_version.yml
> +    runs-on: ubuntu-22.04
```suggestion
    runs-on: ubuntu-latest
```

2024-02-04 07:29 UTC, CodeChenL commented on .github/workflows/release.yml
> +    runs-on: ubuntu-22.04
```suggestion
    runs-on: ubuntu-latest
```

2024-02-04 07:29 UTC, CodeChenL commented on .github/workflows/release.yml
> +    runs-on: ubuntu-22.04
```suggestion
    runs-on: ubuntu-latest
```

2024-02-04 07:48 UTC, RadxaYuntian requested changes

2024-02-04 07:48 UTC, RadxaYuntian commented on Makefile
> +yolov8n.onnx:
```suggestion
examples/yolov8/model/yolov8n.onnx:
```
makefile的对象是完整路径，否则你再次运行会再次下载&转换

2024-02-04 07:48 UTC, RadxaYuntian commented on debian/control
> + wget,
字母顺序排序
numpy是运行时依赖吧？这个以及python要放到包的Recommends里面

2024-02-04 07:48 UTC, RadxaYuntian commented on debian/control
> + ${shlibs:Depends},
Depends应该加上对应的rknpu2的依赖，Recommends加上python3-rknnlite2

https://github.com/radxa-pkg/rknn2/releases

2024-02-04 07:48 UTC, RadxaYuntian commented on debian/control
> +Description: `RKNN Model Zoo` is developed based on the RKNPU SDK toolchain
Description第一行是一个单行简介，第二行开始才是一整个长介绍。另外这不是Markdown，没有\`\`语法

2024-02-04 07:48 UTC, RadxaYuntian commented on debian/patches/0002-Add-rknnlite-support-for-yolov8.patch
> ++sys.path.append(os.path.join(realpath[0]+_sep, *realpath[1:realpath.index('rknn-model-zoo')+1]))
由于其他脚本可能也是这样写的，那么文件安装路径改成rknn_model_zoo好了

2024-02-04 07:48 UTC, RadxaYuntian commented on debian/patches/0002-Add-rknnlite-support-for-yolov8.patch
> ++    parser.add_argument('--target', type=str, default=None, help='target RKNPU platform')
这种就不要改了吧，保持默认执行的行为和上游一致

2024-02-04 07:48 UTC, RadxaYuntian commented on debian/rknn-model-zoo-rk3566.install
> +examples/yolov8/model/yolov8_rk3566.rknn    /usr/share/rknn-model-zoo/examples/yolov8/model/
makefile里面把转换的模型放到别的目录里面（比如./build并gitignore），这样install文件就可以直接复制examples/yolov8/整个目录
再把install文件改用dh-exec，将转换后的模型文件安装成yolov8.rknn，这样程序使用默认参数可以正常执行
顺便测试一下./build-linux.sh能不能在设备上执行

2024-02-04 07:58 UTC, CodeChenL commented on debian/control
> + wget,
numpy转换时用得上

2024-02-04 08:05 UTC, RadxaYuntian commented on debian/control
> + wget,
既然是编译依赖那就保留，然后看看运行时差哪些

2024-02-04 08:46 UTC, CodeChenL commented on debian/control
> + wget,
转换模型需要用到python，这加到Recommends里面吗？

2024-02-04 08:53 UTC, RadxaYuntian commented on debian/control
> + wget,
我们目前不考虑用户在自己设备上进行模型转换的操作，所以这一类的依赖都是Build-Depends
包Depends对应的rknpu2包，但客户可能用C来使用模型，所以运行时的python依赖属于Recommends

2024-02-04 08:56 UTC, CodeChenL commented on debian/control
> + wget,
可是这里不就是Build-Depends:

2024-02-04 08:59 UTC, RadxaYuntian commented on debian/control
> + wget,
我之前问你你说是编译依赖的回复给删了，然后我第二个回复就说“既然是编译依赖那就保留”

2024-02-04 09:03 UTC, CodeChenL commented on debian/patches/0002-Add-rknnlite-support-for-yolov8.patch
> ++    parser.add_argument('--target', type=str, default=None, help='target RKNPU platform')
这里不改的话，lite运行的时候因为多一个--target参数会报错

2024-02-04 09:15 UTC, RadxaYuntian commented on debian/patches/0002-Add-rknnlite-support-for-yolov8.patch
> ++    parser.add_argument('--target', type=str, default=None, help='target RKNPU platform')
需要在rknn_executor那边进行适配

2024-02-04 09:21 UTC, CodeChenL commented on debian/rknn-model-zoo-rk3566.install
> +examples/yolov8/model/yolov8_rk3566.rknn    /usr/share/rknn-model-zoo/examples/yolov8/model/
./build-linux.sh需要在手动转换rknn模型后运行

2024-02-04 09:22 UTC, CodeChenL commented on debian/rknn-model-zoo-rk3566.install
> +examples/yolov8/model/yolov8_rk3566.rknn    /usr/share/rknn-model-zoo/examples/yolov8/model/
主要作用是用来编译so的

2024-02-04 09:23 UTC, RadxaYuntian commented on debian/rknn-model-zoo-rk3566.install
> +examples/yolov8/model/yolov8_rk3566.rknn    /usr/share/rknn-model-zoo/examples/yolov8/model/
我们打包不用编译，只是提供给用户在产品上可以编译就好。这个仓库是一个实例库，以源代码形式提供就可以

2024-02-04 09:25 UTC, RadxaYuntian commented on debian/rknn-model-zoo-rk3566.install
> +examples/yolov8/model/yolov8_rk3566.rknn    /usr/share/rknn-model-zoo/examples/yolov8/model/
另外这些共通的支持代码可以用一个rknn-model-zoo-common包来提供，然后再通过几个soc包依赖这个包并提供转换好的模型。

2024-02-04 09:25 UTC, CodeChenL commented on debian/rknn-model-zoo-rk3566.install
> +examples/yolov8/model/yolov8_rk3566.rknn    /usr/share/rknn-model-zoo/examples/yolov8/model/
.so,我们的apt仓库有提供，这部分源码不用打包吧

2024-02-04 09:28 UTC, RadxaYuntian commented on debian/rknn-model-zoo-rk3566.install
> +examples/yolov8/model/yolov8_rk3566.rknn    /usr/share/rknn-model-zoo/examples/yolov8/model/
cmake脚本有依赖3rdparty目录。算了还是不要提供cpp示例了

2024-02-04 11:38 UTC, RadxaYuntian requested changes

2024-02-04 11:38 UTC, RadxaYuntian commented on debian/control
> + python3-numpy,
这些应该是recommends

2024-02-04 11:38 UTC, RadxaYuntian commented on debian/control
> + rknpu2-rk3588,
这个应该是depends，没有rknpu2模型是不能使用的

2024-02-04 11:38 UTC, RadxaYuntian commented on debian/control
> + rknn-model-zoo-common,
显式指定的应该在shlibs和misc前面

2024-02-04 11:38 UTC, RadxaYuntian commented on debian/control
> +Description: RKNN Model Zoo for RK3588
```suggestion
Description: RKNN Model Zoo Common Files
```

2024-02-04 11:38 UTC, RadxaYuntian commented on debian/patches/0001-Add-rknnlite-support.patch
> ++        if RKNNLite:
if RKNNLite || target==None

2024-02-04 11:38 UTC, RadxaYuntian commented on debian/control
> - python3-numpy,
convert.py依赖这个，不要删

2024-02-04 11:38 UTC, RadxaYuntian commented on debian/control
>   mesa-utils,
libdebhelper-perl, libglib2.0-0, mesa-utils都在哪里用到了？

2024-02-04 11:41 UTC, CodeChenL commented on debian/control
>   mesa-utils,
convert.py转换时会报找不到libglib和libgl

2024-02-04 11:41 UTC, CodeChenL commented on debian/control
>   mesa-utils,
libdebhelper-perl已经改成dh-exec了

2024-02-04 11:53 UTC, RadxaYuntian requested changes

2024-02-04 11:53 UTC, RadxaYuntian commented on .gitignore
> +rknn_toolkit2*.whl
```suggestion
*.whl
```

2024-02-04 11:53 UTC, RadxaYuntian commented on Makefile
> +distclean: clean
按照我们其他项目的make对象的顺序来排，clean是在build后面的

2024-02-04 11:53 UTC, RadxaYuntian commented on debian/control
> + wget,
首字母排序

2024-02-04 11:53 UTC, RadxaYuntian commented on debian/control
> + python3-numpy,
recommends

2024-02-04 11:53 UTC, RadxaYuntian commented on debian/patches/0002-Add-rknnlite-support-for-yolov8.patch
> ++            img = np.expand_dims(img, 0)
这一步是必须的么？

2024-02-04 11:53 UTC, RadxaYuntian commented on debian/rknn-model-zoo-common.install
> +py_utils/ /usr/share/rknn_model_zoo/
把[datasets](https://github.com/radxa-pkg/rknn_model_zoo/tree/main/datasets)目录也加上，模型转换我看了下用到了这个数据。放一起方便用户使用

2024-02-04 11:54 UTC, RadxaYuntian commented on debian/control
> + python3-numpy,
另外首字母排序

2024-02-04 11:55 UTC, CodeChenL commented on debian/patches/0002-Add-rknnlite-support-for-yolov8.patch
> ++            img = np.expand_dims(img, 0)
必须的，不然会报错，输入数据是三维，但是模型是四维

2024-02-04 12:01 UTC, RadxaYuntian requested changes

2024-02-04 12:01 UTC, RadxaYuntian commented on debian/patches/0002-Add-rknnlite-support-for-yolov8.patch
> ++            input_data = img
```suggestion
+            input_data = np.expand_dims(img, 0)
```
这边先这样看看，等rknn联机调试可以后再来看看是不是用完整版是不用添加额外维度

2024-02-04 12:01 UTC, RadxaYuntian commented on debian/patches/0002-Add-rknnlite-support-for-yolov8.patch
> +@@ -256,6 +268,9 @@ if __name__ == '__main__':
```suggestion
@@ -256,6 +268,8 @@ if __name__ == '__main__':
```

2024-02-04 12:03 UTC, CodeChenL commented on debian/patches/0002-Add-rknnlite-support-for-yolov8.patch
> ++            input_data = img
rknn-toolkit2支持模拟器运行

2024-02-04 12:31 UTC, CodeChenL commented
在模拟器上测试，只能先加载原始模型，再build(),不能直接加载rknn模型。所以无法测试需不需要加维度，只能等待连板调试了

2024-02-05 03:22 UTC, RadxaYuntian commented on debian/rknn-model-zoo-common.install
> +py_utils/ /usr/share/rknn_model_zoo/
dataset

2024-02-05 03:22 UTC, RadxaYuntian commented on debian/rknn-model-zoo-common.install
> +py_utils/ /usr/share/rknn_model_zoo/
看到了

2024-02-05 03:51 UTC, RadxaYuntian requested changes

2024-02-05 03:51 UTC, RadxaYuntian commented on debian/changelog
> + -- "Radxa Computer Co., Ltd" <dev@radxa.com>  Wed, 31 Jan 2024 15:47:28 +0800
日期更新一下，然后把commit历史重写

2024-02-05 06:28 UTC, RadxaYuntian approved these changes

2024-02-05 06:29 UTC, merged